name: flutter_hooks_riverpod_app
description: A sample fintech app using hooks_riverpod
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.3
  hooks_riverpod: ^2.4.0
  flutter_riverpod: ^2.6.1
  http: ^1.4.0
#  firebase_core: ^2.16.0
#  firebase_messaging: ^14.7.2
  web_socket_channel: ^2.4.0
  dio: ^5.8.0+1
  flutter_bloc: ^9.1.1
  firebase_core: ^3.14.0
  firebase_messaging: ^15.2.7
  flutter_local_notifications: ^19.3.0 # to show notifications when the app is in foreground
  permission_handler: ^12.0.0+1
  location: ^8.0.1
#  latlong2: ^0.9.1
  flutter_map: ^8.1.1
  #to implement google maps in the app
  google_maps_flutter: ^2.12.3
  geolocator: ^14.0.1
  flutter_polyline_points: ^2.0.0
  hive_flutter: ^1.1.0
  hive: ^2.2.3
  path_provider: ^2.1.5


dev_dependencies:
  bloc_test: ^10.0.0
  mocktail: ^1.0.4
  hive_generator: ^2.0.1
  build_runner: ^2.4.6 
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
